sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - next

language: node_js

cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  include:
    - node_js: "11"
      env: JOB_PART=lint
    - node_js: "11"
      env: JOB_PART=test:only
    - node_js: "10"
      env: JOB_PART=test:only
    - node_js: "6"
      env: JOB_PART=test:only
    - node_js: "4"
      env: JOB_PART=test:only

before_install:
  - npm install -g npm@latest

install:
  - npm ci

before_script:
  - node --version
  - npm --version

script:
  - npm run $JOB_PART
